VAR formulaName = "updateWorkflowStatus ";
DEBUGMESSAGE(formulaName,"START");

VAR result;
var SQL = "SELECT COUNT(*) FROM FWT_12_WORKFLOW_RUN WHERE in_PROGRESS = 1";
result = SQLEXECUTE(SQL,NULL,{});
DEBUGMESSAGE(formulaName, "Trovati "+result [0][0]+" con stato in progress");

SQL = "UPDATE FWT_12_WORKFLOW_RUN SET in_PROGRESS = 0";
SQLEXECUTE(SQL,NULL,{});

DEBUGMESSAGE(formulaName, "Stato workflow aggiornato");
DEBUGMESSAGE(formulaName,"END");

return now();