VAR formulaName = "[LIB_EWS_BE.INDICATOR_50.fe] ";
DEBUGMESSAGE(formulaName, "START");

VAR sql = "";

sql = "

CAST(CASE
                WHEN NULLIF(FLG_BANKRUPT_APPL_GROUP , '') IS NULL THEN 0
                ELSE 1  
END AS CHAR(1)) AS IND_50,

CASE
WHEN NULLIF(FLG_BANKRUPT_APPL_GROUP , '') IS NULL THEN 'E0001 ;' ELSE ''
END AS ERROR_MSG_IND_50
";

 


DEBUGMESSAGE(formulaName, sql);
DEBUGMESSAGE(formulaName, "END");

return sql;
