VAR formulaName = "[LIB_EWS_BE.INDICATOR_20.fe] ";
DEBUGMESSAGE(formulaName, "START");

VAR sql = "";

sql = "

CAST(CAST(CASE
                WHEN FLG_MISSING_FIN_STAT IS NULL THEN 0
                ELSE FLG_MISSING_FIN_STAT 
		END AS INTEGER) AS CHAR(1)) AS IND_20,
		
		CASE
			WHEN FLG_MISSING_FIN_STAT IS NULL THEN 'E0001 ' ELSE ''
		END AS ERROR_MSG_IND_20

";


DEBUGMESSAGE(formulaName, sql);
DEBUGMESSAGE(formulaName, "END");

return sql;
