VAR formulaName = "[LIB_EWS_BE.INDICATOR_174.fe] ";
DEBUGMESSAGE(formulaName, "START");

VAR sql = "";

sql = "CAST(CASE 
           WHEN NULLIF(INFLOWS_ACCOUNT_M0,'') IS NULL THEN 0
           WHEN NULLIF(OVERDRAFT_LIMIT_M0,'') IS NULL THEN 0
           WHEN INFLOWS_ACCOUNT_M0 > (OVERDRAFT_LIMIT_M0*3) THEN 1
           ELSE 0

END AS CHAR(1)) AS IND_174";


DEBUGMESSAGE(formulaName, sql);
DEBUGMESSAGE(formulaName, "END");

return sql;
