VAR formulaName = "[LIB_EWS_BE.INDICATOR_217.fe] ";
DEBUGMESSAGE(formulaName, "START");

VAR sql = "";

sql = "

CAST(
CASE
                WHEN OVERDRAFT_EXCEEDED IS NULL THEN 0
                ELSE OVERDRAFT_EXCEEDED 
END AS DECIMAL(10,0)) AS IND_217,
CASE
	WHEN OVERDRAFT_EXCEEDED IS NULL THEN 'E0001 ' ELSE ''
END AS ERROR_MSG_IND_217

";


DEBUGMESSAGE(formulaName, sql);
DEBUGMESSAGE(formulaName, "END");

return sql;
