VAR formulaName = "[LIB_EWS_BE.INDICATOR_68.fe] ";
DEBUGMESSAGE(formulaName, "START");

VAR sql = "";

sql = "CASE
                WHEN (SALES_Y0 = 0 AND MAX_TOT_DEBT_1Y>0) THEN NULL
                WHEN (SALES_Y0 = 0 AND MAX_TOT_DEBT_1Y<0) THEN NULL
                WHEN (SALES_Y0 = 0 AND MAX_TOT_DEBT_1Y=0) THEN NULL
		ELSE (MAX_TOT_DEBT_1Y / SALES_Y0)
END AS IND_68";


DEBUGMESSAGE(formulaName, sql);
DEBUGMESSAGE(formulaName, "END");

return sql;
