VAR formulaName = "[LIB_EWS_BE.INDICATOR_193.fe] ";
DEBUGMESSAGE(formulaName, "START");

VAR sql = "";

sql = "CASE
                WHEN NULLIF(LOANS_OVERDUE, '') IS NULL THEN 0
                ELSE LOANS_OVERDUE 
END AS IND_193,
CASE
WHEN NULLIF(LOANS_OVERDUE, '') IS NULL THEN 'ERROR; ' ELSE ''
END AS ERROR_MSG_IND_193";


DEBUGMESSAGE(formulaName, sql);
DEBUGMESSAGE(formulaName, "END");

return sql;
