VAR formulaName = "[LIB_EWS_BE.INDICATOR_16.fe] ";
DEBUGMESSAGE(formulaName, "START");

VAR sql = "";

sql = "

CAST(CASE
                WHEN FLG_DEFAULT_STATUS IS NULL THEN 0
                ELSE FLG_DEFAULT_STATUS 
END AS CHAR(1)) AS IND_16,

CASE
WHEN FLG_DEFAULT_STATUS IS NULL THEN 'E0001 ' ELSE ''
END AS ERROR_MSG_IND_16";


DEBUGMESSAGE(formulaName, sql);
DEBUGMESSAGE(formulaName, "END");

return sql;
