VAR formulaName = "[LIB_EWS_BE.INDICATOR_55.fe] ";
DEBUGMESSAGE(formulaName, "START");

VAR sql = "";

sql = "

CAST (CASE
			WHEN FORBORNE_NPE IS NULL THEN 0
			WHEN FORBORNE_NPE > 0 THEN 1
			ELSE 0
	  END AS CHAR(1)) AS IND_55,

(CASE
	WHEN FORBORNE_NPE IS NULL THEN 'E0001 ;' ELSE ''
END ) AS ERROR_MSG_IND_55

";


DEBUGMESSAGE(formulaName, sql);
DEBUGMESSAGE(formulaName, "END");

return sql;
