VAR formulaName = "[LIB_EWS_BE.INDICATOR_115.fe] ";
DEBUGMESSAGE(formulaName, "START");

VAR sql = "";

sql = "CASE
                WHEN (SALES_Y0 = 0 AND NET_INCOME_Y0 >0) THEN NULL
                WHEN (SALES_Y0 = 0 AND NET_INCOME_Y0 <0) THEN NULL
                WHEN (SALES_Y0 = 0 AND NET_INCOME_Y0 =0) THEN NULL
		ELSE (NET_INCOME_Y0 / SALES_Y0)
END AS IND_115";


DEBUGMESSAGE(formulaName, sql);
DEBUGMESSAGE(formulaName, "END");

return sql;
