VAR formulaName = "[LIB_EWS_BE.INDICATOR_64.fe] ";
DEBUGMESSAGE(formulaName, "START");

VAR sql = "";

sql = "CASE
                WHEN (EBITDA_Y0 = 0 AND TOTAL_DEBT_Y0 >0) THEN NULL
                WHEN (EBITDA_Y0 = 0 AND TOTAL_DEBT_Y0 <0) THEN NULL
                WHEN (EBITDA_Y0 = 0 AND TOTAL_DEBT_Y0 =0) THEN NULL
		ELSE (TOTAL_DEBT_Y0/EBITDA_Y0)
END AS IND_64";


DEBUGMESSAGE(formulaName, sql);
DEBUGMESSAGE(formulaName, "END");

return sql;
