call drop_table_if_exists('FWS_01_PROFILE_MAPPING')
/

CREATE TABLE FWS_01_PROFILE_MAPPING
  (
	SYSTEM_PROFILE 	VARCHAR2(50),
	AAAP_PROFILE	VARCHAR2(50)
  )
/
ALTER TABLE FWS_01_PROFILE_MAPPING
ADD CONSTRAINT FWS_01_PROFILE_MAPPING_PK PRIMARY KEY 
(
  SYSTEM_PROFILE 
, AAAP_PROFILE 
)
ENABLE
/
CREATE TABLE SEM_BATCH (STATUS VARCHAR(30) )
/