Insert into EWSA_OWN.FWS_01_PROFILE_MAPPING (SYSTEM_PROFILE,AAAP_PROFILE) values ('YAKK01','administratorProfile')
/
Insert into EWSA_OWN.FWS_01_PROFILE_MAPPING (SYSTEM_PROFILE,AAAP_PROFILE) values ('YAKK01','claimsanalyst')
/
Insert into EWSA_OWN.FWS_01_PROFILE_MAPPING (SYSTEM_PROFILE,AAAP_PROFILE) values ('YAKK02','claimsanalyst')
/
Insert into EWSA_OWN.FWS_01_PROFILE_MAPPING (SYSTEM_PROFILE,AAAP_PROFILE) values ('YAKK02','productionProfile')
/
Insert into EWSA_OWN.FWS_01_PROFILE_MAPPING (SYSTEM_PROFILE,AAAP_PROFILE) values ('YAKK03','claimsanalyst')
/
Insert into EWSA_OWN.FWS_01_PROFILE_MAPPING (SYSTEM_PROFILE,AAAP_PROFILE) values ('YAKK04','core_group_admin')
/
Insert into EWSA_OWN.FWS_01_PROFILE_MAPPING (SYSTEM_PROFILE,AAAP_PROFILE) values ('YAKK04','group1')
/
commit
/
