INSERT into FWS_01_PROFILE_MAPPING (SYSTEM_PROFILE,AAAP_PROFILE) values ('YAKK01','standardgroup')
/
INSERT into FWS_01_PROFILE_MAPPING (SYSTEM_PROFILE,AAAP_PROFILE) values ('YAKK01','riskanalyst')
/
INSERT into FWS_01_PROFILE_MAPPING (SYSTEM_PROFILE,AAAP_PROFILE) values ('YAKK02','riskanalyst')
/
INSERT into FWS_01_PROFILE_MAPPING (SYSTEM_PROFILE,AAAP_PROFILE) values ('YAKK02','superusergroup')
/
INSERT into FWS_01_PROFILE_MAPPING (SYSTEM_PROFILE,AAAP_PROFILE) values ('YAKK03','riskanalyst')
/
INSERT into FWS_01_PROFILE_MAPPING (SYSTEM_PROFILE,AAAP_PROFILE) values ('YAKK03','readonlygroup')
/
INSERT into FWS_01_PROFILE_MAPPING (SYSTEM_PROFILE,AAAP_PROFILE) values ('YAKK04','core_group_admin')
/
INSERT into FWS_01_PROFILE_MAPPING (SYSTEM_PROFILE,AAAP_PROFILE) values ('YAKK04','group1')
/
INSERT into FWS_01_PROFILE_MAPPING (SYSTEM_PROFILE,AAAP_PROFILE) values ('YAKK04','datascientist')
/
commit
/
