VAR formulaName = "[LIB_EWS_IT.INDICATOR_78.fe] ";
DEBUGMESSAGE(formulaName, "START");

VAR sql = "";

sql = "


CAST(
	CASE WHEN COLOR_PD IS NULL THEN NULL
		 WHEN COLOR_PD = 'rosso' THEN
		 WHEN COLOR_PD = 'arancione' THEN 
		 ELSE '' 
	END AS CHAR(10)) AS IND_78,

CASE WHEN COLOR_PD IS NULL THEN 'STRESS001'
	 ELSE ''
END AS ERROR_MSG_IND_78
	
";

DEBUGMESSAGE(formulaName, sql);
DEBUGMESSAGE(formulaName, "END");

return sql;