# FENull returnNull LIB_RISK.updateOutputIrisTable;
# RETURN VALUE: FENull      -
# EFFETCS:      -           updateAnalyticaltable
# Param1:       FEInstance      analysisUnit instance id

DEBUGMESSAGE("LIB_RISK_EW.updateOutputIrisTable.fe"); # stacktrace


VAR analysisUnitID = Param1;

IF (analysisUnitID == "CUSTOMER") THEN {
	LIB_EWS_IT.updateOutputIrisTable_IT(analysisUnitID);
}
else {
	DEBUGMESSAGE("LIB_RISK_EW.updateOutputIrisTable.fe Formula not found "+analysisUnitID)
}


return now();