# FENull returnNull LIB_RISK_EW.backTesting;
# RETURN VALUE: FENull      -
# EFFETCS:      -           updateAnalyticaltable
# Param1:       FEInstance      analysisUnit instance id

DEBUGMESSAGE("LIB_RISK_EW.backTesting.fe"); # stacktrace

VAR analysisUnitID = Param1;

IF (analysisUnitID == "CUSTOMER") THEN {
	LIB_EWS_IT.backTesting_IT(analysisUnitID);
}
else {
	DEBUGMESSAGE("LIB_RISK_EW.backTesting.fe Formula not found "+analysisUnitID)
}


return now();