
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.i4c.isp.auth.ws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-09-28T12:48:06.568+02:00
 * Generated source version: 3.0.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "Service",
                      portName = "ServiceSoap",
                      targetNamespace = "http://sanpaoloimi.com/SSO",
                      wsdlLocation = "file:WSDLProfile.wsdl",
                      endpointInterface = "com.i4c.isp.auth.ws.ServiceSoap")
                      
public class ServiceSoapImpl implements ServiceSoap {

    private static final Logger LOG = Logger.getLogger(ServiceSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see com.i4c.isp.auth.ws.ServiceSoap#getCache(*
     */
    public java.lang.String getCache() { 
        LOG.info("Executing operation getCache");
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.i4c.isp.auth.ws.ServiceSoap#getProfile2(java.lang.String  token ,)java.lang.String  siteName ,)java.lang.String  timeStamp ,)java.lang.String  encodedPwd ,)java.lang.String  encodedType ,)java.lang.String  filter )*
     */
    public java.lang.String getProfile2(java.lang.String token,java.lang.String siteName,java.lang.String timeStamp,java.lang.String encodedPwd,java.lang.String encodedType,java.lang.String filter) { 
        LOG.info("Executing operation getProfile2");
        System.out.println(token);
        System.out.println(siteName);
        System.out.println(timeStamp);
        System.out.println(encodedPwd);
        System.out.println(encodedType);
        System.out.println(filter);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
