package com.i4c.isp.auth.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-09-28T12:48:06.621+02:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://sanpaoloimi.com/SSO", name = "ServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceSoap {

    /**
     * Returns the cached abilitations.
     */
    @WebResult(name = "GetCacheResult", targetNamespace = "http://sanpaoloimi.com/SSO")
    @RequestWrapper(localName = "GetCache", targetNamespace = "http://sanpaoloimi.com/SSO", className = "com.i4c.isp.auth.ws.GetCache")
    @WebMethod(operationName = "GetCache", action = "http://sanpaoloimi.com/SSO/GetCache")
    @ResponseWrapper(localName = "GetCacheResponse", targetNamespace = "http://sanpaoloimi.com/SSO", className = "com.i4c.isp.auth.ws.GetCacheResponse")
    public java.lang.String getCache();

    /**
     * Returns a user profile for a given OU in the current AD forest.
     */
    @WebResult(name = "GetProfile2Result", targetNamespace = "http://sanpaoloimi.com/SSO")
    @RequestWrapper(localName = "GetProfile2", targetNamespace = "http://sanpaoloimi.com/SSO", className = "com.i4c.isp.auth.ws.GetProfile2")
    @WebMethod(operationName = "GetProfile2", action = "http://sanpaoloimi.com/SSO/GetProfile2")
    @ResponseWrapper(localName = "GetProfile2Response", targetNamespace = "http://sanpaoloimi.com/SSO", className = "com.i4c.isp.auth.ws.GetProfile2Response")
    public java.lang.String getProfile2(
        @WebParam(name = "Token", targetNamespace = "http://sanpaoloimi.com/SSO")
        java.lang.String token,
        @WebParam(name = "SiteName", targetNamespace = "http://sanpaoloimi.com/SSO")
        java.lang.String siteName,
        @WebParam(name = "TimeStamp", targetNamespace = "http://sanpaoloimi.com/SSO")
        java.lang.String timeStamp,
        @WebParam(name = "EncodedPwd", targetNamespace = "http://sanpaoloimi.com/SSO")
        java.lang.String encodedPwd,
        @WebParam(name = "EncodedType", targetNamespace = "http://sanpaoloimi.com/SSO")
        java.lang.String encodedType,
        @WebParam(name = "Filter", targetNamespace = "http://sanpaoloimi.com/SSO")
        java.lang.String filter
    );
}
