package com.i4c.isp.auth.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * Web service di profilazione forest level
 *
 * This class was generated by Apache CXF 3.0.4
 * 2015-09-28T12:48:06.664+02:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "Service", 
                  wsdlLocation = "file:WSDLProfile.wsdl",
                  targetNamespace = "http://sanpaoloimi.com/SSO") 
public class Service extends javax.xml.ws.Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://sanpaoloimi.com/SSO", "Service");
    public final static QName ServiceSoap = new QName("http://sanpaoloimi.com/SSO", "ServiceSoap");
    public final static QName ServiceSoap12 = new QName("http://sanpaoloimi.com/SSO", "ServiceSoap12");
    public final static QName ServiceHttpPost = new QName("http://sanpaoloimi.com/SSO", "ServiceHttpPost");
    public final static QName ServiceHttpGet = new QName("http://sanpaoloimi.com/SSO", "ServiceHttpGet");
    static {
        URL url = null;
        try {
            url = new URL("file:WSDLProfile.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:WSDLProfile.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns ServiceSoap
     */
    @WebEndpoint(name = "ServiceSoap")
    public ServiceSoap getServiceSoap() {
        return super.getPort(ServiceSoap, ServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceSoap
     */
    @WebEndpoint(name = "ServiceSoap")
    public ServiceSoap getServiceSoap(WebServiceFeature... features) {
        return super.getPort(ServiceSoap, ServiceSoap.class, features);
    }
    /**
     *
     * @return
     *     returns ServiceSoap
     */
    @WebEndpoint(name = "ServiceSoap12")
    public ServiceSoap getServiceSoap12() {
        return super.getPort(ServiceSoap12, ServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceSoap
     */
    @WebEndpoint(name = "ServiceSoap12")
    public ServiceSoap getServiceSoap12(WebServiceFeature... features) {
        return super.getPort(ServiceSoap12, ServiceSoap.class, features);
    }
    /**
     *
     * @return
     *     returns ServiceHttpPost
     */
    @WebEndpoint(name = "ServiceHttpPost")
    public ServiceHttpPost getServiceHttpPost() {
        return super.getPort(ServiceHttpPost, ServiceHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceHttpPost
     */
    @WebEndpoint(name = "ServiceHttpPost")
    public ServiceHttpPost getServiceHttpPost(WebServiceFeature... features) {
        return super.getPort(ServiceHttpPost, ServiceHttpPost.class, features);
    }
    /**
     *
     * @return
     *     returns ServiceHttpGet
     */
    @WebEndpoint(name = "ServiceHttpGet")
    public ServiceHttpGet getServiceHttpGet() {
        return super.getPort(ServiceHttpGet, ServiceHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceHttpGet
     */
    @WebEndpoint(name = "ServiceHttpGet")
    public ServiceHttpGet getServiceHttpGet(WebServiceFeature... features) {
        return super.getPort(ServiceHttpGet, ServiceHttpGet.class, features);
    }

}
