
package com.i4c.isp.auth.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-09-28T12:48:06.526+02:00
 * Generated source version: 3.0.4
 * 
 */
public final class ServiceSoap_ServiceSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://sanpaoloimi.com/SSO", "Service");

    private ServiceSoap_ServiceSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        
    	if(args.length == 0){
    		System.err.println("Invalid Params");
    		System.exit(-1);
    	}
    	
        URL wsdlURL = new URL(args[0]);
        Service ss = new Service(wsdlURL, SERVICE_NAME);
        ServiceSoap port = ss.getServiceSoap12();  

        System.out.println("Invoking getCache...");
        java.lang.String _getCache__return = port.getCache();
        System.out.println("getCache.result=" + _getCache__return);

        java.lang.String _getProfile2_token = null;
        java.lang.String _getProfile2_siteName = null;
        java.lang.String _getProfile2_timeStamp = null;
        java.lang.String _getProfile2_encodedPwd = null;
        java.lang.String _getProfile2_encodedType = null;
        java.lang.String _getProfile2_filter = null;
        
        for(int i = 1 ; i < args.length ; i++){
        	String key = args[i].split("=")[0];
        	String value = args[i].split("=")[1];
        	
        	if(key.equalsIgnoreCase("token")){
        		_getProfile2_token = value;
        	}
        	else if(key.equalsIgnoreCase("siteName")){
        		_getProfile2_siteName = value;
        	}
        	else if(key.equalsIgnoreCase("timeStamp")){
        		_getProfile2_timeStamp = value;
        	}
        	else if(key.equalsIgnoreCase("encodedPwd")){
        		_getProfile2_encodedPwd = value;
        	}
        	else if(key.equalsIgnoreCase("encodedType")){
        		_getProfile2_encodedType = value;
        	}
        	else if(key.equalsIgnoreCase("filter")){
        		_getProfile2_filter = value;
        	}
        }
        System.out.println("Invoking getProfile2...");
       
        java.lang.String _getProfile2__return = port.getProfile2(_getProfile2_token, _getProfile2_siteName, _getProfile2_timeStamp, _getProfile2_encodedPwd, _getProfile2_encodedType, _getProfile2_filter);
        System.out.println("getProfile2.result=" + _getProfile2__return);

        System.exit(0);
    }

}
