package com.i4c.isp.auth.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-09-28T12:48:06.632+02:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://sanpaoloimi.com/SSO", name = "ServiceHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ServiceHttpPost {

    /**
     * Returns the cached abilitations.
     */
    @WebResult(name = "string", targetNamespace = "http://sanpaoloimi.com/SSO", partName = "Body")
    @WebMethod(operationName = "GetCache")
    public java.lang.String getCache();

    /**
     * Returns a user profile for a given OU in the current AD forest.
     */
    @WebResult(name = "string", targetNamespace = "http://sanpaoloimi.com/SSO", partName = "Body")
    @WebMethod(operationName = "GetProfile2")
    public java.lang.String getProfile2(
        @WebParam(partName = "Token", name = "Token", targetNamespace = "http://sanpaoloimi.com/SSO")
        java.lang.String token,
        @WebParam(partName = "SiteName", name = "SiteName", targetNamespace = "http://sanpaoloimi.com/SSO")
        java.lang.String siteName,
        @WebParam(partName = "TimeStamp", name = "TimeStamp", targetNamespace = "http://sanpaoloimi.com/SSO")
        java.lang.String timeStamp,
        @WebParam(partName = "EncodedPwd", name = "EncodedPwd", targetNamespace = "http://sanpaoloimi.com/SSO")
        java.lang.String encodedPwd,
        @WebParam(partName = "EncodedType", name = "EncodedType", targetNamespace = "http://sanpaoloimi.com/SSO")
        java.lang.String encodedType,
        @WebParam(partName = "Filter", name = "Filter", targetNamespace = "http://sanpaoloimi.com/SSO")
        java.lang.String filter
    );
}
