VAR formulaName = "[LIB_EWS_IT.INDICATOR_80.fe] ";
DEBUGMESSAGE(formulaName, "START");

VAR sql = "";

sql = "


NVL(IND_81,'S00') 	AS X,
NVL(IND_82,'S00') 	AS Y,
NVL(IND_83,'S00')   AS Z,

CASE
	 when (Y<=X and X<=Z) or (Z<=X and X<=Y) then X,
	 when (X<=Y and Y<=Z) or (Z<=Y and Y<=X) then Y,
	 when (X<=Z and Z<=Y) or (Y<=Z and Z<=X) then Z
END AS IND_80,

	'' AS ERROR_MSG_IND_80

";

DEBUGMESSAGE(formulaName, sql);
DEBUGMESSAGE(formulaName, "END");

return sql;