//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.06 at 03:40:43 PM CEST 
//


package com.isp.auth.ws.response;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ProfileResponse }
     * 
     */
    public ProfileResponse createString() {
        return new ProfileResponse();
    }

    /**
     * Create an instance of {@link ProfileResponse.SpiProfilingWS }
     * 
     */
    public ProfileResponse.SpiProfilingWS createStringSpiProfilingWS() {
        return new ProfileResponse.SpiProfilingWS();
    }

    /**
     * Create an instance of {@link ProfileResponse.SpiProfilingWS.Userinfo }
     * 
     */
    public ProfileResponse.SpiProfilingWS.Userinfo createStringSpiProfilingWSUserinfo() {
        return new ProfileResponse.SpiProfilingWS.Userinfo();
    }

    /**
     * Create an instance of {@link ProfileResponse.SpiProfilingWS.Userinfo.Userprofile }
     * 
     */
    public ProfileResponse.SpiProfilingWS.Userinfo.Userprofile createStringSpiProfilingWSUserinfoUserprofile() {
        return new ProfileResponse.SpiProfilingWS.Userinfo.Userprofile();
    }

    /**
     * Create an instance of {@link ProfileResponse.SpiProfilingWS.Userinfo.Userprofile.Privileges }
     * 
     */
    public ProfileResponse.SpiProfilingWS.Userinfo.Userprofile.Privileges createStringSpiProfilingWSUserinfoUserprofilePrivileges() {
        return new ProfileResponse.SpiProfilingWS.Userinfo.Userprofile.Privileges();
    }

    /**
     * Create an instance of {@link ProfileResponse.SpiProfilingWS.Userinfo.Userprofile.Privileges.Privilege }
     * 
     */
    public ProfileResponse.SpiProfilingWS.Userinfo.Userprofile.Privileges.Privilege createStringSpiProfilingWSUserinfoUserprofilePrivilegesPrivilege() {
        return new ProfileResponse.SpiProfilingWS.Userinfo.Userprofile.Privileges.Privilege();
    }

}
