//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.06 at 03:40:43 PM CEST 
//


package com.isp.auth.ws.response;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SpiProfilingWS">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="userinfo">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="userprofile">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="privileges">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="privilege">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="bank" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="branch" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "spiProfilingWS"
})
@XmlRootElement(name = "string")
public class ProfileResponse {

    @XmlElement(name = "SpiProfilingWS", required = true)
    protected ProfileResponse.SpiProfilingWS spiProfilingWS;

    /**
     * Gets the value of the spiProfilingWS property.
     * 
     * @return
     *     possible object is
     *     {@link ProfileResponse.SpiProfilingWS }
     *     
     */
    public ProfileResponse.SpiProfilingWS getSpiProfilingWS() {
        return spiProfilingWS;
    }

    /**
     * Sets the value of the spiProfilingWS property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProfileResponse.SpiProfilingWS }
     *     
     */
    public void setSpiProfilingWS(ProfileResponse.SpiProfilingWS value) {
        this.spiProfilingWS = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="userinfo">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="userprofile">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="privileges">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="privilege">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                           &lt;attribute name="bank" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="branch" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "userinfo"
    })
    public static class SpiProfilingWS {

        @XmlElement(required = true)
        protected ProfileResponse.SpiProfilingWS.Userinfo userinfo;

        /**
         * Gets the value of the userinfo property.
         * 
         * @return
         *     possible object is
         *     {@link ProfileResponse.SpiProfilingWS.Userinfo }
         *     
         */
        public ProfileResponse.SpiProfilingWS.Userinfo getUserinfo() {
            return userinfo;
        }

        /**
         * Sets the value of the userinfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link ProfileResponse.SpiProfilingWS.Userinfo }
         *     
         */
        public void setUserinfo(ProfileResponse.SpiProfilingWS.Userinfo value) {
            this.userinfo = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="userprofile">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="privileges">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="privilege">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *                 &lt;attribute name="bank" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="branch" type="{http://www.w3.org/2001/XMLSchema}int" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "userprofile"
        })
        public static class Userinfo {

            @XmlElement(required = true)
            protected ProfileResponse.SpiProfilingWS.Userinfo.Userprofile userprofile;
            @XmlAttribute(name = "name")
            protected java.lang.String name;

            /**
             * Gets the value of the userprofile property.
             * 
             * @return
             *     possible object is
             *     {@link ProfileResponse.SpiProfilingWS.Userinfo.Userprofile }
             *     
             */
            public ProfileResponse.SpiProfilingWS.Userinfo.Userprofile getUserprofile() {
                return userprofile;
            }

            /**
             * Sets the value of the userprofile property.
             * 
             * @param value
             *     allowed object is
             *     {@link ProfileResponse.SpiProfilingWS.Userinfo.Userprofile }
             *     
             */
            public void setUserprofile(ProfileResponse.SpiProfilingWS.Userinfo.Userprofile value) {
                this.userprofile = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link java.lang.String }
             *     
             */
            public java.lang.String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link java.lang.String }
             *     
             */
            public void setName(java.lang.String value) {
                this.name = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="privileges">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="privilege">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *       &lt;attribute name="bank" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="branch" type="{http://www.w3.org/2001/XMLSchema}int" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "privileges"
            })
            public static class Userprofile {

                @XmlElement(required = true)
                protected ProfileResponse.SpiProfilingWS.Userinfo.Userprofile.Privileges privileges;
                @XmlAttribute(name = "bank")
                protected Integer bank;
                @XmlAttribute(name = "branch")
                protected Integer branch;

                /**
                 * Gets the value of the privileges property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link ProfileResponse.SpiProfilingWS.Userinfo.Userprofile.Privileges }
                 *     
                 */
                public ProfileResponse.SpiProfilingWS.Userinfo.Userprofile.Privileges getPrivileges() {
                    return privileges;
                }

                /**
                 * Sets the value of the privileges property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link ProfileResponse.SpiProfilingWS.Userinfo.Userprofile.Privileges }
                 *     
                 */
                public void setPrivileges(ProfileResponse.SpiProfilingWS.Userinfo.Userprofile.Privileges value) {
                    this.privileges = value;
                }

                /**
                 * Gets the value of the bank property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getBank() {
                    return bank;
                }

                /**
                 * Sets the value of the bank property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setBank(Integer value) {
                    this.bank = value;
                }

                /**
                 * Gets the value of the branch property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getBranch() {
                    return branch;
                }

                /**
                 * Sets the value of the branch property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setBranch(Integer value) {
                    this.branch = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="privilege">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "privilege"
                })
                public static class Privileges {

                    @XmlElement(required = true)
                    protected List<ProfileResponse.SpiProfilingWS.Userinfo.Userprofile.Privileges.Privilege> privilege;

                    /**
                     * Gets the value of the privilege property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link ProfileResponse.SpiProfilingWS.Userinfo.Userprofile.Privileges.Privilege }
                     *     
                     */
                    public List<ProfileResponse.SpiProfilingWS.Userinfo.Userprofile.Privileges.Privilege> getPrivilege() {
                        return privilege;
                    }

                    /**
                     * Sets the value of the privilege property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link ProfileResponse.SpiProfilingWS.Userinfo.Userprofile.Privileges.Privilege }
                     *     
                     */
                    public void setPrivilege(List<ProfileResponse.SpiProfilingWS.Userinfo.Userprofile.Privileges.Privilege> value) {
                        this.privilege = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "")
                    public static class Privilege {

                        @XmlAttribute(name = "name")
                        protected java.lang.String name;

                        /**
                         * Gets the value of the name property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link java.lang.String }
                         *     
                         */
                        public java.lang.String getName() {
                            return name;
                        }

                        /**
                         * Sets the value of the name property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link java.lang.String }
                         *     
                         */
                        public void setName(java.lang.String value) {
                            this.name = value;
                        }

                    }

                }

            }

        }

    }

}
