VAR nodes = LIB_VMCommons.getDefaultNodeGroupsConf();
var dataPreparation = nodes[2];
dataPreparation = get(dataPreparation,"nodes");
VAR node =  [ "name" : "Transform Woe",       "ports" : "I/O", "actions" : { ["name" : "Edit", "targetPage" : "transformWoe", "enableApply" : true], ["name" : "Show Data", "targetPage" : "showData"]} ];
addelement(dataPreparation,node);
#debugmessage(MAPTOJSONSTRING(dataPreparation));

return nodes;