package com.i4c.isp.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-11-10T10:37:30.863+01:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://service.isp.i4c.com/", name = "executeDailyBatch")
@XmlSeeAlso({ObjectFactory.class})
public interface ExecuteDailyBatch {

    @WebResult(name = "Result", targetNamespace = "")
    @RequestWrapper(localName = "executeWorkflow", targetNamespace = "http://service.isp.i4c.com/", className = "com.i4c.isp.client.ExecuteWorkflow")
    @WebMethod
    @ResponseWrapper(localName = "executeWorkflowResponse", targetNamespace = "http://service.isp.i4c.com/", className = "com.i4c.isp.client.ExecuteWorkflowResponse")
    public java.lang.String executeWorkflow(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
