package com.i4c.isp.client;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.0.4 2015-11-10T10:37:30.803+01:00
 * Generated source version: 3.0.4
 * 
 */
public final class ExecuteDailyBatchClient {

	private static final QName SERVICE_NAME = new QName(
			"http://service.isp.i4c.com/", "executeDailyBatchWS");

	private ExecuteDailyBatchClient() {
	}

	public static void main(String args[]) {
		URL wsdlURL = null;
		String workflowName = null;
		if (args.length != 2) {
			System.err.println("Invalid Input, set WSDL URL and workflow name");
			System.exit(-1);
		}

		try {
			wsdlURL = new URL(args[0]);
			workflowName = args[1];

			ExecuteDailyBatchWS ss = new ExecuteDailyBatchWS(wsdlURL,SERVICE_NAME);
			ExecuteDailyBatch port = ss.getExecuteDailyBatchPort();

			System.out.println("Invoking executeWorkflow " + workflowName);
			String workflowRreturn = port.executeWorkflow(workflowName);
			System.out.println("executeWorkflow result="+workflowRreturn);
			
			System.exit(0);

		} catch (MalformedURLException e) {
			System.err.println("Invalid Input, check WSDL URL");
			System.exit(-1);
		}
		catch (Exception e) {
			System.err.println("EExecution error: "+e.getMessage());
			System.exit(-1);
		}

	}

}
