package com.i4c.isp.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-11-10T10:37:30.863+01:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "executeDailyBatchWS", 
                  wsdlLocation = "file:/c:/Dati/DEV/Doc/Intesa/WSDL_BATCH.wsdl",
                  targetNamespace = "http://service.isp.i4c.com/") 
public class ExecuteDailyBatchWS extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.isp.i4c.com/", "executeDailyBatchWS");
    public final static QName ExecuteDailyBatchPort = new QName("http://service.isp.i4c.com/", "executeDailyBatchPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/c:/Dati/DEV/Doc/Intesa/WSDL_BATCH.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ExecuteDailyBatchWS.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/c:/Dati/DEV/Doc/Intesa/WSDL_BATCH.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ExecuteDailyBatchWS(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ExecuteDailyBatchWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExecuteDailyBatchWS() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ExecuteDailyBatchWS(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ExecuteDailyBatchWS(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ExecuteDailyBatchWS(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns ExecuteDailyBatch
     */
    @WebEndpoint(name = "executeDailyBatchPort")
    public ExecuteDailyBatch getExecuteDailyBatchPort() {
        return super.getPort(ExecuteDailyBatchPort, ExecuteDailyBatch.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExecuteDailyBatch
     */
    @WebEndpoint(name = "executeDailyBatchPort")
    public ExecuteDailyBatch getExecuteDailyBatchPort(WebServiceFeature... features) {
        return super.getPort(ExecuteDailyBatchPort, ExecuteDailyBatch.class, features);
    }

}
