VAR formulaName = "[LIB_EWS_RETAIL.INDICATOR_90.fe] ";
DEBUGMESSAGE(formulaName, "START");

VAR sql = "";

sql = 

"
CAST(
	CASE 
		WHEN IND_91 IS NULL AND
			 IND_92 IS NULL AND
			 IND_93 IS NULL AND
			 IND_94 IS NULL THEN '0'
		ELSE '1'
	END AS CHAR(1)) AS IND_90,
	
	CAST(NULL AS VARCHAR(20)) AS ERROR_MSG_IND_90
		

";

DEBUGMESSAGE(formulaName, sql);
DEBUGMESSAGE(formulaName, "END");

return sql;

