VAR formulaName = "[LIB_EWS_RETAIL.INDICATOR_29.fe] ";
DEBUGMESSAGE(formulaName, "START");

VAR sql = "";

sql = "


CAST(
	CASE 
		WHEN FLG_ROTTURA_COVE = 'X' THEN cast (CURRENT_DATE as integer) - cast(COVE_INIZIO_ROTTURA_DT as integer)
		ELSE null
	END AS DECIMAL(10,0)) AS IND_29,
	
CAST(NULL AS VARCHAR(20)) AS ERROR_MSG_IND_29


";

DEBUGMESSAGE(formulaName, sql);
DEBUGMESSAGE(formulaName, "END");

return sql;


