VAR formulaName = "[LIB_EWS_IT.INDICATOR_84.fe] ";
DEBUGMESSAGE(formulaName, "START");

VAR sql = "";

sql = "
cast(
	case 
		when ESP_FL_RATA_ARRETRATA is null then '0'
		else ESP_FL_RATA_ARRETRATA
	end as char(1)) AS IND_84	
, 
CASE when ESP_FL_RATA_ARRETRATA is null then 'ESP000_1'
		else ''
END AS ERROR_MSG_IND_84

";


DEBUGMESSAGE(formulaName, sql);
DEBUGMESSAGE(formulaName, "END");

return sql;