VAR formulaName = "[LIB_EWS_IT.IND_512_OVER.fe] ";
DEBUGMESSAGE(formulaName, "START");

VAR sql = "";

sql = "
CAST(
		CASE 		
			WHEN VAL_BR_512_OVERRIDE is null then null
			ELSE (IND_12 - VAL_BR_512_OVERRIDE) 		
		END AS DECIMAL(30,12)) AS IND_512_OVER,
		
		(CASE 
			WHEN VAL_BR_512_OVERRIDE is null then ''
			ELSE ''	
		END ) AS ERROR_MSG_IND_512_OVER
";

DEBUGMESSAGE(formulaName, sql);
DEBUGMESSAGE(formulaName, "END");

return sql;
