VAR formulaName = "[LIB_EWS_IT.IND_139_OVER.fe] ";
DEBUGMESSAGE(formulaName, "START");

VAR sql = "";

sql = "
CAST(
		CASE WHEN VAL_BR_139_OVERRIDE is not null THEN (IND_37 - VAL_BR_139_OVERRIDE)
			 ELSE null
		END AS DECIMAL(30,12)) AS IND_139_OVER,
		
		(CASE
			WHEN VAL_BR_139_OVERRIDE is not null THEN ''
			 ELSE ''
		END ) AS ERROR_MSG_IND_139_OVER
";


DEBUGMESSAGE(formulaName, sql);
DEBUGMESSAGE(formulaName, "END");

return sql;
