VAR formulaName = "[LIB_EWS_IT.IND_FL_DATE6M.fe] ";
DEBUGMESSAGE(formulaName, "START");

VAR sql = "";

sql = "

	CAST(
		CASE 
			WHEN (( CURRENT_DATE  - DATA_OVERRIDE) > 180)  THEN 1
			ELSE 0 
		END AS CHAR(1)) AS IND_FL_DATE6M ,
		
		(CASE
			WHEN ((CURRENT_DATE  - DATA_OVERRIDE) > 180)  THEN ''
			ELSE '' 
		END) AS ERROR_MSG_IND_FL_DATE6M
		
";


DEBUGMESSAGE(formulaName, sql);
DEBUGMESSAGE(formulaName, "END");

return sql;