VAR formulaName = "[LIB_EWS_IT.IND_118_FL_SUPER.fe] ";
DEBUGMESSAGE(formulaName, "START");

VAR sql = "";

sql = "
CAST(
		CASE 
			WHEN VAL_BR_118_OVERRIDE  = '1' THEN '1'
			ELSE '0' 
		END AS CHAR(1)) AS IND_118_FL_SUPER,
		
		(CASE
			WHEN VAL_BR_118_OVERRIDE  = '1' THEN ''
			ELSE ''
		END ) AS ERROR_MSG_IND_118_FL_SUPER
";


DEBUGMESSAGE(formulaName, sql);
DEBUGMESSAGE(formulaName, "END");

return sql;

