VAR formulaName = "[LIB_EWS_IT.INDICATOR_88.fe] ";
DEBUGMESSAGE(formulaName, "START");

VAR sql = "";

sql = "

cast(
	case 
		when ESP_FL_SCONFINO_CTPY_RED is null then '0'
		else ESP_FL_SCONFINO_CTPY_RED
	end as char(1)) AS IND_88	
,
CASE when ESP_FL_SCONFINO_CTPY_RED is null then 'ESP005_1'
		else ''
END AS ERROR_MSG_IND_88
";


DEBUGMESSAGE(formulaName, sql);
DEBUGMESSAGE(formulaName, "END");

return sql;