VAR formulaName = "[LIB_EWS_IT.IND_512_FL_OVERRIDE.fe] ";
DEBUGMESSAGE(formulaName, "START");

VAR sql = "";

sql = "
CAST(
		CASE 
			WHEN BR_512_OVERRIDE  = '0' THEN '1'
              ELSE '0'  
		END AS CHAR(1)) AS IND_512_FL_OVERRIDE,
		
		(CASE
			WHEN BR_512_OVERRIDE  = '0' THEN '1'
			ELSE ''
		END ) AS ERROR_MSG_IND_512_FL_OVERRIDE
";


DEBUGMESSAGE(formulaName, sql);
DEBUGMESSAGE(formulaName, "END");

return sql;