VAR formulaName = "[LIB_EWS_IT.IND_142_OVER.fe] ";
DEBUGMESSAGE(formulaName, "START");

VAR sql = "";

sql = "
CAST(
		CASE WHEN VAL_BR_142_OVERRIDE is not null THEN (IND_39 - VAL_BR_142_OVERRIDE)
			 ELSE null
		END AS DECIMAL(30,12)) AS IND_142_OVER,
		
		(CASE
			WHEN VAL_BR_142_OVERRIDE is not null THEN ''
			 ELSE ''
		END ) AS ERROR_MSG_IND_142_OVER
";


DEBUGMESSAGE(formulaName, sql);
DEBUGMESSAGE(formulaName, "END");

return sql;
