VAR formulaName = "[LIB_EWS_IT.IND_525_OVER.fe] ";
DEBUGMESSAGE(formulaName, "START");

VAR sql = "";

sql = "
CAST(
		CASE 		
			WHEN VAL_BR_525_OVERRIDE is null or VAL_BR_525_OVERRIDE = 0 then null
			ELSE (CDS_SPREAD_5Y / VAL_BR_525_OVERRIDE)-1 		
		END AS DECIMAL(30,12)) AS IND_525_OVER,
		
		(CASE 
			WHEN VAL_BR_525_OVERRIDE is null then ''
			ELSE ''	
		END ) AS ERROR_MSG_IND_525_OVER
";

DEBUGMESSAGE(formulaName, sql);
DEBUGMESSAGE(formulaName, "END");

return sql;
