VAR formulaName = "[LIB_EWS_IT.IND_12_CHANGE.fe] ";
DEBUGMESSAGE(formulaName, "START");

VAR sql = "";

sql = "
CAST(
		CASE 
			WHEN BR12_LAST_RUN = 1 AND IND_12 < 0.1 THEN 1
			ELSE 0 
		END AS CHAR(1)) AS IND_12_CHANGE,
		
		(CASE
			WHEN BR12_LAST_RUN = 1 AND IND_12 < 0.1 THEN ''
			ELSE ''
		END ) AS ERROR_MSG_IND_12_CHANGE
";

DEBUGMESSAGE(formulaName, sql);
DEBUGMESSAGE(formulaName, "END");

return sql;