var formulaName = "[CreateVariableSQL.validate] ";
DEBUGMESSAGE(formulaName, "START");

var user = Param1;
var routerMap = Param2;
var symbolTable = Param3;

var all_page_labels = LIB_Label.predictiveApp('VisualModeling');

var validations = NULL;

if (symbolTable['nodeValue'] <> NULL){
    if (is_empty(symbolTable['nodeValue']['variableLabelName']) ){
        validations = [
            "widgets" : {},
            "notifications" : {
                [ "type" : "warning", "title" : all_page_labels["LABEL_NOT_SET"], "message" : "", "autoHide" : true]
            }
        ];
    }
}

DEBUGMESSAGE(formulaName, "END");
return validations;
