VAR formulaName = "[LIB_EWS.UpdateCustomerUnitOutput]";
DEBUGMESSAGE(formulaName, "START");

VAR units = Customer_Unit;
Var formula;
VAR logActionName	= "UpdateCustomerUnitOutput";
foreach(units as unit){
	formula = unit.UpdateOutTable_Formula;
	
	SAVE_LOG("Info", logActionName, "Update Output: "+unit.NAME);
	
	if(LENGTH(formula) > 0 ){
		EVAL(formula,{unit});
	}
}

DEBUGMESSAGE(formulaName, "END");